### ISSUE TITLE
Rename hosts to nodes

### ISSUE THREAD

**Issue by ogenstad** [brigade-automation/brigade#118]
Rename:

host -> node
hosts -> nodes

To keep things more generic.

**Comment by ktbyers** [comment]
I like `host` quite a bit better than node (i.e. it is the term I expect to use in this context). To me they cover the same set of referents (i.e. one is not more generic than the other).

**Comment by ktbyers** [comment]
So your definition of `node` is just any endpoint? So the distinction between node and host is that node would encompass API endpoints?

I guess I have a different definition of node (as I am not seeing in your analogy how the use of node would clarify the situation).

That being said...I don't care much one way or the other (so have at it, if you both want to change it).

**Comment by ogenstad** [comment]
From a pure terminology point of view I would look at it like this:

```python
class Node:
    pass

class Host(Node):
    pass
```

In that sense I see node as a more generic object than host.

**Comment by ogenstad** [comment]
I didn’t mean that we should use both. Only that I view node as a broader more generic definition that host.

**Comment by ktbyers** [comment]
Okay, no worries...totally misunderstood what you were saying there :-)

But now it makes sense.

**Comment by ktbyers** [comment]
What is a datapoint?

This seemed like a strange way of phrasing this sentence:

`making the relevant data for that node (and its parents groups) available` (which makes me worried I am not following how you intend things to be used).

**Comment by ogenstad** [comment]
A datapoint would be a fancy name for variables or properties. :)

**Comment by ktbyers** [comment]
Okay, makes sense...I was still thinking in terms of things (nodes/hosts) and not in terms of attributes.

**Comment by dbarrosop** [comment]
Ok, even though I think we kind of agree `Node` is the correct term, after updating most of the code/examples/docs/etc everything becomes a bit confusing so I think I am going to close this ticket and maybe add some documentation (eventually) using examples where we use brigade outside the realm of "hosts automation".
