### ISSUE TITLE
Consistent handling for task arguments

### ISSUE THREAD

**Issue by ogenstad** [brigade-automation/brigade#20]
A little followup for the discussion in #17.

Regarding having username and password etc, as arguments in tasks or only based on information from the inventory my first use case will be to use Brigade as part of a network discovery process. I will have a number of ip addresses and a number of different sets of credentials. I won't know which credentials to use for each of the device and will have to each one until I find something which works. In that scenario I wouldn't want the credentials to be tied to the inventory, i.e. it would be good to have both where the task arguments would override the inventory.

I do however like the idea of reusing the logic between different tasks so that we don't invent the wheel for each set of tasks.

Also for consistency I think we should enforce the naming of common arguments so they remain the same for all tasks.

As an example I used `host` as an argument for the `tcp_ping` task. The similar argument with `napalm_cli` is `hostname`, for the netmiko task it's `ip` or `host`. I think all of these only use one argument and that it should be host instead of hostname or ip, the reason being that a host could be either an ip address or a hostname.

Also I think we should standardise other arguments too, for example that all tasks use `username` instead of having some tasks with `username` and others with `user`, `api_user` or something else.

A starting list for this could be (examples actual names can be changed):

* host
* username
* password
* ignore_certs
* http_proxy
* https_proxy
* device_type
* filename
* destination

Ping @dbarrosop, @ktbyers.

**Comment by dbarrosop** [comment]
Regarding names, I agree. That's why I added the `host` properties for `host`, `username`, etc... to make sure they are named consistently and they are also resolved in the same way.

**Comment by dbarrosop** [comment]
I think we can close this one, right?
