### ISSUE TITLE
decorator for tasks

### ISSUE THREAD

**Issue by dbarrosop** [brigade-automation/brigade#75]
I was wondering if we should have a decorator for tasks where we can signal things. For instance:

```
@brigade.plugins.task(dry_run=True, format_agruments=["filename"])
def napalm_configure(task, filename=None, configuration=None, replace=False):
    ....

@brigade.plugins.task(dry_run=None, format_agruments=[])
def print_result(task, data, vars=None, failed=None, task_id=None):
```

Basically arguments of the decorators indicate that:

a. Whether the task supports `dry_run` or not or if it doesn't apply
b. Which arguments should be auto-formatted (an alternative to #53)
c. Others that might come, maybe?

**Comment by ogenstad** [comment]
Could perhaps also use decorators later to handle the try/except statements from https://github.com/napalm-automation/brigade/pull/77#issuecomment-363729919 as a way of avoiding having redundant code in various plugins.

**Comment by dbarrosop** [comment]
I am going to close this one for now as I don't see an immediate need. Right now most of the logic can be enclosed in the `start` method (https://github.com/brigade-automation/brigade/pull/98/files#diff-118676f40dc730bc62bf5d116683f4abR42). The main purpose for a decorator would be to allow "configuring" the behavior of tasks. For instance, #97, which I am not sure we want.
