### ISSUE TITLE
add requests task

### ISSUE THREAD

**Issue by dbarrosop** [brigade-automation/brigade#93]
Would be nice to have a task wrapping requests

**Comment by ogenstad** [comment]
Like one that took `method` as an argument and you can get, put, post, delete and such?

**Comment by dbarrosop** [comment]
exactly

**Comment by ogenstad** [comment]
Something like this might make sense to have both as a `task` and as a `function`, i.e something which shares common code.

**Comment by dbarrosop** [comment]
haha yeah, my current implementation (which I will submit soon) looks exactly like that :)

**Comment by dbarrosop** [comment]
Solve in #96
